services:
  app:
    build:
      context: .
    restart: unless-stopped
    container_name: chat-ai-backend
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
