services:
  chat-ai-backend-dclavijo45:
    build:
      context: .
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 10
    expose:
      - ${PORT}
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
    networks:
      - cloudflared

networks:
  cloudflared:
    external: true

